#!/usr/bin/env python
'''
    cropdb
    ——————

    Initialisation code.

    :copyright: (c) 2015 by Anshul Sirur.
'''
from cropdb import app

if app.config['DEBUG_MODE']:
    app.debug = True

app.run()
